config/routes.rb
Rails.application.routes.draw do
  root to: 'plans#index'
  resources :plans
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :plan_users
  has_many :users, through: :plan_users, dependent: :destroy

  # 
  validates :title, presence: true, length: { maximum: 15 }

  # 
  with_options presence: true do
    validates :start_time
    validates :ending_time
    validates :date_pattern
  end

  # 
  validates :comment, presence: true, length: { maximum: 500 }
end

app/models/plan_user.rb
class PlanUser < ApplicationRecord
  belongs_to :plan
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plan_users
  has_many :plans, through: :plan_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all
    @plan = Plan.new
  end

  def new
    @plan = Plan.new
    @plans = Plan.all
  end

  def create
    #binding.pry
    @plan = Plan.new(plan_params)
    #binding.pry
    if @plan.save
      #binding.pry
      redirect_to root_path
    else
      #binding.pry
      @plans = Plan.all
      render :index
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan = Plan.find(params[:id])
    @plans = Plan.all
  end

  def update
    binding.pry
    @plan = Plan.find(params[:id])
    binding.pry
    if @plan.update(edit_plan_params)
      binding.pry
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    binding.pry
    if @plan.destroy
      redirect_to root_path
    else
      redirect_to :show
    end
  end

  private

  def plan_params
    params.permit( :title, :start_time, :ending_time, :date_pattern, :comment, user_ids: []).merge(master_id: current_user.id)
  end

  def edit_plan_params
    params.require(:plan).permit( :title, :start_time, :ending_time, :date_pattern, :comment, user_ids: []).merge(master_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PlanApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/plans/edit.html.erb
<div class="header">
  <%= render "shared/header" %>
</div>

<div class="wrapper">

  <%#メインフォーム部分 %>
  <%= render "shared/main_form" %>
  <%#メインフォーム部分 %>

  <%#サイドフォーム部分%>
  <div class="side-form">

    <%#サイドヘッダー部分%>
    <div class="side-header edit-header">
      予定の変更はこちらから
    </div>
    <%#サイドヘッダー部分%>

    <%#予定入力フォーム%>
    <div class="input-form">
      <%= form_with model: @plan, local: true do |form| %>

        <div class="title">
          <div class="column-name">
            タイトル
          </div>
          <div class="column-input">
            <%= form.text_field :title, class:"input-title", placeholder:"（例）資格取得目標シートの提出（40文字まで）" %>
          </div>
        </div>

        <div class="time">
          <div class="data-pattern">
            <%= form.radio_button :date_pattern, :"通常" %>
            <%= form.label :date_pattern, "通常", { value: "通常", style: :"display: inline-block;"} %>
            <%= form.radio_button :date_pattern, :"締切" %>
            <%= form.label :date_pattern, "締切", { value: "締切", style: :"display: inline-block;"} %>
            <%= form.radio_button :date_pattern, :"終日" %>
            <%= form.label :date_pattern, "終日", { value: "終日", style: :"display: inline-block;"} %>
          </div>
          <div class="start-time">
            <div class="column-name">
              開始時間
            </div>
            <div class="column-input">
              <%= form.datetime_select :start_time, class:"input-time" %>
            </div>
          </div>
          <div class="ending-time">
            <div class="column-name">
              終了時間
            </div>
            <div class="column-input">
              <%= form.datetime_select :ending_time, class:"input-time"  %>
            </div>
          </div>
        </div>

        <div class="user">
          <% 5.times do |t| %>
          <div class="column-user">
            <div class="column-name">
              <%= "参加者#{t+1}"%>
            </div>
            <div class="column-input">
              <select name="user_ids[]">
                <option value="">選択してください</option>
                <% User.where.not(id: current_user.id).each do |user| %>
                  <option value=<%= user.id %>><%= user.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <% end %>
          <input name="user_ids[]" type="hidden" value=<%= current_user.id%>>
        </div>

        <div class="comment">
          <div>
            コメント（注意事項など）
          </div>
          <%= form.text_area :comment, rows:"9", maxlength:"500",  class:"input-comment", placeholder:"（例）\n田中もしくは鈴木に直接提出をお願いします。\n遅れる場合は締め切り日前日までにご連絡をお願いいたします。\n(500文字まで)" %>
        </div>

        <div class="submit">
          <%= form.submit "更新", class:"btn btn-warning btn-lg"%>
        </div>
      <% end %>
    </div>
    <%#予定入力フォーム%>

  </div>
  <%#サイドフォーム部分%>
</div>

app/views/plans/index.html.erb
<div class="header">
  <%= render "shared/header" %>
</div>

<div class="wrapper">

  <%#メインフォーム部分 %>
  <%= render "shared/main_form" %>
  <%#メインフォーム部分 %>
    
  <%# 詳細ページフォーム %>
  <%#= render "shared/show" %>
  <%# 詳細ページフォーム %>

  <%#サイドフォーム部分%>
  <%= render "shared/side_form" %>
  <%#サイドフォーム部分%>
</div>

app/views/plans/new.html.erb
<%#サイドヘッダー部分%>
    <div class="side-header">
      予定の入力はこちらから
    </div>
    <%#サイドヘッダー部分%>

    <%#予定入力フォーム%>
    <div class="input-form">
      <%= form_with url: plans_path, local: true do |form| %>

        <div class="title">
          <div class="column-name">
            タイトル
          </div>
          <div class="column-input">
            <%= form.text_field :title, class:"input-title", placeholder:"（例）資格取得目標シートの提出（40文字まで）" %>
          </div>
        </div>

        <div class="time">
          <div class="data-pattern">
            <%= form.radio_button :date_pattern, :"通常" %>
            <%= form.label :date_pattern, "通常", { value: "通常", style: :"display: inline-block;"} %>
            <%= form.radio_button :date_pattern, :"締切" %>
            <%= form.label :date_pattern, "締切", { value: "締切", style: :"display: inline-block;"} %>
            <%= form.radio_button :date_pattern, :"終日" %>
            <%= form.label :date_pattern, "終日", { value: "終日", style: :"display: inline-block;"} %>
          </div>
          <div class="start-time">
            <div class="column-name">
              開始時間
            </div>
            <div class="column-input">
              <%= form.datetime_select :start_time, class:"input-time" %>
            </div>
          </div>
          <div class="ending-time">
            <div class="column-name">
              終了時間
            </div>
            <div class="column-input">
              <%= form.datetime_select :ending_time, class:"input-time"  %>
            </div>
          </div>
        </div>

        <div class="user">
          <% 5.times do |t| %>
          <div class="column-user">
            <div class="column-name">
              <%= "参加者#{t+1}"%>
            </div>
            <div class="column-input">
              <select name="user_ids[]">
                <option value="">選択してください</option>
                <% User.where.not(id: current_user.id).each do |user| %>
                  <option value=<%= user.id %>><%= user.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <% end %>
          <input name="user_ids[]" type="hidden" value=<%= current_user.id%>>
        </div>

        <div class="comment">
          <div>
            コメント（注意事項など）
          </div>
          <%= form.text_area :comment, rows:"9", maxlength:"500",  class:"input-comment", placeholder:"（例）\n田中もしくは鈴木に直接提出をお願いします。\n遅れる場合は締め切り日前日までにご連絡をお願いいたします。\n(500文字まで)" %>
        </div>

        <div class="submit">
          <%= form.submit "登録", class:"btn btn-success btn-lg"%>
        </div>
      <% end %>
    </div>
    <%#予定入力フォーム%>

app/views/plans/show.html.erb
<div class="plan-info">
  <div class="info-header">
    <div>
      <h1><%= @plan.title %></h1>
      <%= "投稿者 #{User.find(@plan.master_id).name}" %>
    </div>
    <div>
      <%= link_to '✖️', root_path, method: :get, class:"close" %>
    </div>
  </div>
  <div class="info-body">
    <div class="info-title" >コメント(詳細事項)</div>
    <div class="well">
      <%= @plan.comment %>
    </div>
    <div class="well">
      <span>開始時間</span>
      <%= @plan.start_time.strftime("%m月%d日 %H:%M") %>
      <span> ~ 終了時間</span>
      <%= @plan.ending_time.strftime("%m月%d日 %H:%M") %>
    </div>
    <div class="info-user-table">
      <span>参加者</span>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>名前</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <% @plan.users.each do |user| %>
          <tr>
            <th><%= link_to "#{user.name}", "#" %></th>
            <th><%= user.email %></th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%# 投稿者（マスター）以外は変更・削除を表示させない %>
  <div class="info-footer">
    <div class="btn-group btn-group-justified">
      <%= link_to '変更', edit_plan_path(@plan), method: :get, class:"btn btn-warning" %>
      <%= link_to '削除', plan_path, method: :delete, class:"btn btn-danger" %>
    </div>
  </div>
  <%# 投稿者（マスター）以外は変更・削除を表示させない %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
   <div class="right-list">
    <h1>Plan-App</h1>
  </div>
  <div class="left-list">
    <% if user_signed_in? %>
      <%= link_to current_user.name, "#" %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to '新規登録', new_user_registration_path, mothod: :get %>
      <%= link_to 'ログイン', new_user_session_path, method: :get %>
    <% end %>
  </div>
</header>

app/views/shared/_main_form.html.erb
  <div class="main-form">

    <%# 検索フォーム部分　%>
    <div class="main-header">
      <div class="select-user">検索したいユーザーを選択してください：
        <% 4.times do |t| %>
        <select name="" id="">
          <option value="--">選択してください</option>
          <% User.all.each do |user| %>
            <option><%= user.name %></option>
          <% end %>
        </select>
        <% end %>
      </div>
    </div>
    <%# 検索フォーム部分　%>

    <%#カレンダー表示部分%>
    <%# Planに予定がない場合はカレンダーのみ表示させる %>
    <div class="calendar">
      <%= month_calendar events: @plans do |date, plans| %>
        <%= date.day %>
        <% plans.each do |plan| %>
          <div>
            <%= link_to(plan_path(plan)) do %>
              <% if plan.date_pattern == "通常" %>
                <%= plan.start_time.strftime("%H:%M") %><span>-</span><%= plan.ending_time.strftime("%H:%M") %>
                <%= plan.title%>
              <% elsif plan.date_pattern == "締切" %>
                <%= plan.ending_time.strftime("%H:%M") %><span>まで</span>
                <%= plan.title %>
              <% else %>
                <%= plan.title %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <%#/カレンダー表示部分%>

  </div>

app/views/shared/_side_form.html.erb
<div class="side-form">

    <%#サイドヘッダー部分%>
    <div class="side-header">
      予定の入力はこちらから
    </div>
    <%#サイドヘッダー部分%>

    <%#予定入力フォーム%>
    <div class="input-form">
      <%= form_with url: plans_path, local: true do |form| %>

        <div class="title">
          <div class="column-name">
            タイトル
          </div>
          <div class="column-input">
            <%= form.text_field :title, class:"input-title", placeholder:"（例）資格取得目標シートの提出（40文字まで）" %>
          </div>
        </div>

        <div class="time">
          <div class="data-pattern">
            <%= form.radio_button :date_pattern, :"通常" %>
            <%= form.label :date_pattern, "通常", { value: "通常", style: :"display: inline-block;"} %>
            <%= form.radio_button :date_pattern, :"締切" %>
            <%= form.label :date_pattern, "締切", { value: "締切", style: :"display: inline-block;"} %>
            <%= form.radio_button :date_pattern, :"終日" %>
            <%= form.label :date_pattern, "終日", { value: "終日", style: :"display: inline-block;"} %>
          </div>
          <div class="start-time">
            <div class="column-name">
              開始時間
            </div>
            <div class="column-input">
              <%= form.datetime_select :start_time, class:"input-time" %>
            </div>
          </div>
          <div class="ending-time">
            <div class="column-name">
              終了時間
            </div>
            <div class="column-input">
              <%= form.datetime_select :ending_time, class:"input-time"  %>
            </div>
          </div>
        </div>

        <div class="user">
          <% 5.times do |t| %>
          <div class="column-user">
            <div class="column-name">
              <%= "参加者#{t+1}"%>
            </div>
            <div class="column-input">
              <select name="user_ids[]">
                <option value="">選択してください</option>
                <% User.where.not(id: current_user.id).each do |user| %>
                  <option value=<%= user.id %>><%= user.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <% end %>
          <input name="user_ids[]" type="hidden" value=<%= current_user.id%>>
        </div>

        <div class="comment">
          <div>
            コメント（注意事項など）
          </div>
          <%= form.text_area :comment, rows:"9", maxlength:"500",  class:"input-comment", placeholder:"（例）\n田中もしくは鈴木に直接提出をお願いします。\n遅れる場合は締め切り日前日までにご連絡をお願いいたします。\n(500文字まで)" %>
        </div>

        <div class="submit">
          <%= form.submit "登録", class:"btn btn-success btn-lg"%>
        </div>
      <% end %>
    </div>
    <%#予定入力フォーム%>

</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading text-center h2 ">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= start_date.year %>年 <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>